### PR TITLE
New Regex to find arbitrary number of links

### PR DESCRIPTION
**Pull request by Aneduna**
This adds a new option suggested by https://github.com/veiset/poe-vendor-string/issues/25
It dynamically creates the regex with the suggested shortening of the regex if one of the values is 0.
From my very limited testing this seems to work, however it very quickly creates lines that are >50 Characters.

New Layout

I'm not a Webdev, so this needs some fixing on the css side of things.
Also please let me know if on the react side of thing there are things to improve

This does not implement the 3 or 4 Link Regex changes that were suggested.

### CODE REVIEW

**Comment by veiset** [comment]
Great work, the code looks good. I think the way it is presented takes a little too much space.

Are you able to structure it this way:
image

(check out the function `SocketCheckbox` for css inspiration 😁, you probably want to expose `imgFromChar` to easily get the image)

**Comment by Aneduna** [comment]
Thanks for the suggestions, I'll look into how I can position it like that.
I'll add the placeholder.

**Comment by veiset** [comment]
I'm heading to work, but I will look at this in around 8 hours.

I'll do some testing and if everything looks good I'll merge and publish it.

**Comment by Aneduna** [comment]
Changed the things. Had a fight with css. If needed I would refactor it if you want, but then it would probably take longer than League start :)

**Comment by veiset** [comment]
This looks very good. Thanks for taking the time to implement it! 

I'll merge it in a few hours and we can always refactor after league start! 😁

**Comment by veiset** [comment]
I did a few small adujstments to the page, check out the commit: 4f1d0ec

Sorry about the delay of publishing the page but github has had some [issues with github-actions](https://www.githubstatus.com/) for the last few hours. I'll publish it as soon as I'm able to.

**Pull request merged**
